#!/usr/bin/env python3
"""Generate `notebooks/iiswc_tutorial.ipynb` from the published attendee page.

The page -- the published site's `instructions.ts` -- is the source of
truth for what the units are, what they run, and what the screen should say. This
script is the transcription of it, so a page change is a data edit here and not a
hand-edit of notebook JSON. **Edit this file, re-run it, commit both.**

    python3 notebooks/tools/build_notebook.py

Fidelity rules kept here on purpose:
  * every command, every expected-output block and every fix is the page's text;
  * nothing is invented where the page says a unit has no attendee sequence;
  * a step's `where` decides which helper runs it -- `lab.sh` on the instance,
    `lab.board` on the card, and nothing at all where the page says the step
    happens at the glass or on a laptop.

Where this is not a transcription
---------------------------------
The page describes the flow in which the attendee joins `iiswc-robotics-tutorial`, holds
a shared SSH key and reaches AWS through their card. The interface moved
(TUTORIAL_INTERFACE_NOTES.md 4e, TUTORIAL_AUTH_TLS.md): the attendee opens JupyterLab on
their own instance and the board connects to that instance. Steps 0.2 and 1.3 are
therefore written for the flow that exists rather than transcribed from the page, and the
page's own "find your instance" step has no counterpart here at all.

The notebook does not narrate that difference: an attendee needs the flow in front of
them, not its history. The page is a separate repository and is edited separately.

Prose style, and the reason this file is the place to fix prose: ordinary sentences, the
command, and what the screen should say. Explain the technical content -- the two harts
and their extensions, what the trace encoder records, what the solver optimises -- and
not how the tutorial's own plumbing is arranged.
"""
import json
from pathlib import Path

NB = Path(__file__).resolve().parents[1] / "iiswc_tutorial.ipynb"

cells: list[dict] = []


def _lines(text: str) -> list[str]:
    """nbformat wants every line but the last to KEEP its newline.

    Splitting on "\\n" and dropping it collapses the whole cell onto one line, which
    looks right in the JSON and is a SyntaxError in the kernel. Caught by executing the
    notebook; it is not visible by reading it.
    """
    parts = text.rstrip("\n").split("\n")
    return [p + "\n" for p in parts[:-1]] + parts[-1:]


def _cell_id() -> str:
    return f"c{len(cells):03d}"


def md(text: str) -> None:
    cells.append({"cell_type": "markdown", "id": _cell_id(), "metadata": {},
                  "source": _lines(text)})


def code(text: str) -> None:
    cells.append({"cell_type": "code", "id": _cell_id(), "execution_count": None,
                  "metadata": {}, "outputs": [], "source": _lines(text)})


def fence(text: str, lang: str = "") -> str:
    return f"```{lang}\n{text}\n```"


def fixes_table(fixes) -> str:
    rows = "\n".join(f"| {s} | {a} |" for s, a in fixes)
    return "**If instead you see**\n\n| | do |\n|---|---|\n" + rows


# ======================================================================================
# Front matter -- instructions.ts `instructions`
# ======================================================================================
md("""# IISWC 2026 · Robotics stack tutorial

Your PYNQ board implements a RISC-V system-on-chip (SoC) in its FPGA. The SoC has two
cores with different instruction extensions. In this tutorial, you will build
applications for it and examine their performance.

This notebook runs on your AWS instance. The instance builds the applications, and
the board runs them. Some exercises use recorded measurements supplied with the notebook.

### Tutorial overview

Complete Unit 0 to check your setup, then work through these five units with your
instructor.

| Unit | What you will do |
|---|---|
| 1. Zephyr and Chipyard | Build a Zephyr application, run it on the board, and capture a camera frame. |
| 2. ModelBlaster | Compile a model, inspect its kernels, and compare scalar and accelerated execution. |
| 3. TACIT | Capture execution on both cores and inspect a recorded timeline. |
| 4. Kernel optimization | Check the correctness and speed of a kernel generated by a language model. |
| 5. XPU-RT | Compare schedules for two models that share the board's cores and memory. |

### Running the exercises

| Helper | Runs on |
|---|---|
| `lab.sh("...")` | this instance |
| `lab.board("verb")` | your board |

`lab.board()` accepts a fixed set of operations. Run `lab.board("help")` to list them.

<details>
<summary>Where the example outputs came from</summary>

The original page records command output from `pynq-2` on 2026-09-23. This notebook
includes board output from a rerun on `pynq-13` on 2026-09-24.

</details>""")

md("""### Find your seat

Read your board's own address from the bottom row of its OLED display. If it shows
`10.42.0.13`, your seat number is 13. The table below uses `N` for your seat number.

| Device | Address or name |
|---|---|
| Your board | `10.42.0.{N}` |
| Its hostname | `pynq-{N}` |
| Your instance | `aws-{N}.iiswc` |

Run the two cells below. The first identifies your AWS instance. The second checks
whether your board is connected.""")

code('''import sys, pathlib, importlib
sys.path.insert(0, str(pathlib.Path.cwd()))
import iiswc_lab as lab
lab = importlib.reload(lab)          # a re-run picks up an updated helper file

lab.where_am_i()''')

code("lab.board_status()")

# ======================================================================================
# Unit 0
# ======================================================================================
md("""---

## Unit 0 · Check your board and its connection

Use the board's display to check that the SoC is running. Then check whether the board
is connected to your AWS instance.""")

md("""### 0.1 Check the board's display

The OLED shows the address of your AWS instance, your board's own address, and an uptime
counter:

""" + fence("https://\n198.51.\n100.197/\n10.42.0.{N} up 4:17") + """

The top three rows are one web address, in the tallest font the panel has. It is the
address of your instance, and the digits carry on from the first row to the second: the
split falls after the second dot, and the dot left hanging at the end of a row is the
continuation cue. Read the rows together, keep the closing slash, and that is the address
to open in your browser.

The bottom row is your board's own address on the room network, followed by the time since
the SoC last booted. Your seat number is the last part of that address: a board showing
`10.42.0.13` is seat 13.

Watch the `up M:SS` field for a few seconds. It counts minutes and seconds since the SoC's
last boot and should keep advancing.

A board that has no instance address to show uses a shorter layout instead: its own
address, the network it joined, and the line `no instance addr` above the uptime counter.

""" + fixes_table([
    ("`up M:SS` stops advancing", "Turn the board off and on again. The counter should restart at `up 0:00`."),
    ("The display shows `NO ADDRESS` or `wlan0 DOWN`.", "Turn the board off and on again, then wait for an IP address to appear."),
    ("The display shows `no instance addr`.", "Your board found the network but not your instance. Turn the board off and on again; it looks for the instance while it boots."),
    ("The display is blank and the board started less than two minutes ago.", "Wait for the display to update. Network startup takes about 37 seconds."),
]))

md("""### 0.2 Check the board's connection

Your board connects to your AWS instance automatically. Run the next cell to check
the connection. You can repeat this check if the board stops responding.""")
code("lab.board_status()")
md("""The check takes about three seconds. Look for `board connected` in the result. The
examples below show a successful connection and two offline states:

""" + fence(
    "board connected -- pynq-13, 10.42.0.13, PL operating, MAGIC -\n"
    "board offline (nothing is listening) -- ConnectionRefusedError ...\n"
    "board offline (tunnel is stale) -- the port is bound but nothing answered within 3s") + """

""" + fixes_table([
    ("`board offline (nothing is listening)`", "The board has not connected yet. Check the OLED as described in 0.1. If the uptime counter has stopped, turn the board off and on again."),
    ("`board offline (tunnel is stale)`", "The board retries the connection automatically. Wait, then run the cell again."),
    ("The board stays offline after a restart.", "Ask an instructor for help. You can continue with exercises that run entirely on the instance."),
]))

# Unit 1
# ======================================================================================
md("""---

## Unit 1 · Zephyr and Chipyard: build and run an application

You will build a Zephyr application for the Rocket SoC, run it on your board, and
capture a camera frame. You will also inspect how Zephyr describes the hardware and
selects drivers.

Your AWS instance provides the build tools. Keep the board connected to the instance
while you upload and run the applications.""")

md("""### 1.1 Run build commands from the notebook

The cells below use `lab.sh` to run shell commands on your AWS instance. If your browser
disconnects, reopen the notebook to continue. The commands run on the instance and can
continue while the browser is disconnected.""")

md("""### 1.2 Build a Zephyr image for the Rocket SoC

Build `samples/boot_info`, the application currently running on your board. It reports
the board's status and network connection. The recorded build took about thirteen
seconds.""")
code('''build = lab.sh("""cd /home/ubuntu/tut && source /home/ubuntu/tut/env.sh && \\
west build -p always -b chipyard_pynqz1_all_f40 \\
    -d ~/out/boot_info samples/boot_info \\
    -- -DBOARD_ROOT=/home/ubuntu/tut""", timeout=900)
if not build.ok:
    raise RuntimeError("the build failed -- read the log above before going on")''')
md("The build ends with a summary of memory use:\n\n" + fence(
    "-- west build: building application\n...\n"
    "Memory region         Used Size  Region Size  %age Used\n"
    "             RAM:       69720 B       256 MB      0.03%"))
code('lab.sh("ls -l ~/out/boot_info/zephyr/zephyr.bin")')
md("Check that the file listing includes `zephyr.bin`. This build produced a 56,888-byte image:\n\n" + fence("-rw-rw-r-- 1 ubuntu ubuntu 56888 ... zephyr.bin"))

md("""### 1.3 Upload the image to the PYNQ board and run it

Upload the image you just built. You will then load the SoC's FPGA configuration,
start the application, and read its console output.""")
code('lab.board_put("/home/ubuntu/out/boot_info/zephyr/zephyr.bin")')
md("""Check that the response reports `ok: true` and that `bytes` matches the file size
from 1.2. The board computes the `md5` checksum of the uploaded image:

""" + fence("""{
  "ok": true,
  "stored": "zephyr.bin",
  "bytes": 56888,
  "md5": "c830b4b6a0d1e4f7c2b9358e6a1d70cf"
}""", "json") + """

Run the next cell to load the FPGA configuration and start the application. This takes
about 40 seconds.""")
code('lab.board("run", "zephyr", timeout=300)')
md("""The board reports the application it ran and the number of console bytes it saved:

""" + fence("""{
  "ok": true,
  "ran": "zephyr",
  "console_bytes": 373,
  "results": ["console.out", "run.log"]
}""", "json") + """

The board saves the console output in `console.out`. Fetch it with the next cell.""")
code('''c = lab.board("get", "console.out", binary=True, verbose=False)
print(lab.console_text(c) or c)''')
md("""Card 13 produced this 373-byte console output on 2026-09-24:

""" + fence(
    "*** Booting Zephyr OS build 4329bf61c4fe ***\n"
    "BI_BOOT addr=0x8f000000\n"
    "BI_RAW magic=0x42533031\n"
    "BI_OLED probe addr=0x3c addr_ack_rc=0 nop_rc=0 init_rc=0 setup_rc=0\n"
    "BI_OLED state=READY addr=0x3c\n"
    "BI_STATUS state=PRESENT nonce=0xa1873611 soc_magic=0x5A5A0038\n"
    "BI_NET host=pynq-13 iface=wlan0 ipv4=10.42.0.13 ssid=iiswc-robotics-tutorial "
    "link_up=1 signal_dbm=-31\n"
    "BI_DONE") + """

Check for `soc_magic=0x5A5A0038` and `BI_DONE`. The magic value identifies the FPGA
configuration used in this unit. Your `nonce` will differ, and the OLED's uptime
counter should restart at `up 0:00`.""")

md("""### 1.4 Take a picture with the board's camera

The shield carries an HM01B0 image sensor. The camera driver configures it, lets
auto-exposure settle, and captures a complete frame into DRAM using DMA.

Build the camera application with the next cell. The master-clock divider of 2 gives
6.67 MHz from the board's 40 MHz clock.""")
code('''build = lab.camera_build()
if not build.ok:
    raise RuntimeError("Camera build failed; inspect the log before uploading")''')
md("""Upload the image and run it. The application reports the sensor ID, measured
frame dimensions, and the address and checksum of the captured bytes.""")
code('''pushed = lab.board_put("/home/ubuntu/out/cam_capture/zephyr/zephyr.bin")
if not pushed.ok:
    raise RuntimeError(f"Camera upload failed: {pushed}")
ran = lab.board("run", "zephyr", timeout=300)
if not ran.ok:
    raise RuntimeError(f"Camera guest failed to run: {ran}")''')
md("""Read the capture results. If the application reports `CAM_ERROR`, check its stage
and reason. A failure marked `reset_required=1` needs a SoC reset before another
capture; the board's `run` command performs one.""")
code('''c = lab.board("get", "console.out", binary=True, verbose=False)
if not c.ok:
    raise RuntimeError(f"Could not read the camera console: {c}")
console = lab.console_text(c)
lab.show_console_lines(console, "CAM_SHIELD", "CAM_SENSOR", "CAM_GEOM",
                       "CAM_FRAME ", "CAM_ERROR", "CAM_RESULT")''')
md("""Successful output has the following form. Addresses and pixel statistics depend
on the build and the scene; these lines illustrate the fields to check.

""" + fence(
    "CAM_SHIELD present=1\n"
    "CAM_SENSOR model_id=0x01b0 ok=1\n"
    "CAM_GEOM src=lastframe width=326 height=324 bytes=105624\n"
    "CAM_FRAME ok=1 rc=0 addr=<Rocket address> phys=<ARM address> width=326 height=324 "
    "bytes=105624 min=<min> max=<max> sum=<checksum> saweof=1 ... bayer=BGGR rotate=180\n"
    "CAM_RESULT shield=1 ok=1") + """

Check three fields in your output:

- `model_id=0x01b0` confirms that the sensor answered on the control bus.
- `saweof=1` confirms that the transfer ended at the sensor's end-of-frame marker.
- `bytes=105624` gives the usual stored frame size: 324 rows of 326 bytes.

Each row contains two leading dummy bytes from the sensor and 324 active pixels.
The application adds every raw byte and reports the total as `sum`. The next section
checks that total before displaying the image.""")

md("""### 1.5 Download and display the frame

The frame is stored in the board's DRAM. The `camera` operation reads it from the
address reported by the application, and `get` transfers the bytes to your instance.
Save the frame only after its length and checksum agree with the capture report.""")
code('''frame = lab.camera_frame_metadata(console)
pulled = lab.board("camera")
if not pulled.ok:
    raise RuntimeError(f"Camera memory read failed: {pulled}")
f = lab.board("get", "frame.raw", binary=True, verbose=False)
if not f.ok:
    raise RuntimeError(f"Could not fetch the camera frame: {f}")
raw_path = lab.camera_save_frame(f.stdout, frame)
print(f"{frame['bytes']:,} bytes, checksum {frame['sum']:,}: verified")''')
md("""The sensor sends a Bayer mosaic: each pixel measures one colour channel.
The display cell runs the complete photo pipeline automatically:

1. Remove the two dummy bytes per row and infer the Bayer colour order from the frame.
2. Subtract the estimated black level and white-balance using unclipped pixels.
3. Reconstruct RGB at full resolution with gradient-corrected demosaicing,
   then suppress colour speckles without smoothing luminance detail.
4. Apply a generic colour-correction matrix at 0.7 strength and soften clipped highlights.
5. Apply the sRGB display curve and rotate for the sensor's mounting.

Colour correction improves the display; the matrix is not a sensor calibration.""")
code('''from IPython.display import Image, display

picture = lab.camera_render_frame(raw_path, frame)
display(Image(filename=str(picture)))''')
md("""You should see a 324 x 324 colour image for a complete 326 x 324 raw frame.
The original bytes remain in `frame.raw`; the displayed image is `frame-colour.png`.

Unit 2's detector uses separate preprocessing to prepare 64 x 64 inputs directly
from the raw frame. Its preprocessing is checked between host and board; the
displayed PNG is not the detector's input.""")

md("""### 1.6 Inspect the hardware description and enabled drivers

Zephyr uses devicetree to describe the hardware and Kconfig to choose which software
components to include. Inspect both for the camera image you just built.

The board files in `boards/chipyard/pynqz1_all_f40` describe the I2C controller at
`0x1004_0000`, the capture unit at `0x1008_0000`, GPIO, six LEDs, and four buttons.
The generated `zephyr.dts` contains the hardware description used by this build.

Run the next cell to find the camera and button nodes in that file.""")
code('''lab.sh("""grep -A7 'ospi@10080000' ~/out/cam_capture/zephyr/zephyr.dts \\
  | sed 's,[[:space:]]*/[*].*[*]/,,' | grep -v '^$' && echo --- && \\
grep -A6 'buttons: buttons' ~/out/cam_capture/zephyr/zephyr.dts \\
  | sed 's,[[:space:]]*/[*].*[*]/,,' | grep -v '^$'""")''')
md("The command prints the camera node followed by the start of the button definitions:\n\n" + fence(
    "ospi0: ospi@10080000 {\n"
    '        compatible = "ucbbar,ospi-hm01b0";\n'
    "        reg = < 0x10080000 0x1000 >;\n"
    "        interrupt-parent = < &plic >;\n"
    "        interrupts = < 0xd 0x1 >;\n"
    "        frame-buffer-depth = < 0x200 >;\n"
    "        sensor-i2c = < &i2c0 >;\n"
    '        status = "okay";\n'
    "---\n"
    "buttons: buttons {\n"
    '        compatible = "gpio-keys";\n'
    "        debounce-interval-ms = < 0x1e >;\n"
    "        btn0: btn0 {\n"
    "                gpios = < &gpio0 0x6 0x0 >;") + """

A driver claims that `compatible` string: `modules/ospi_camera`. Every field in the node
is something the driver reads. `reg` gives the register block's address.
`frame-buffer-depth` is the capture unit's 512-beat buffer, which holds one line rather
than one frame. `interrupts` records the interrupt the unit raises, which this driver does
not connect because it polls. `sensor-i2c` points at the I2C controller the sensor's
control port is on, and the driver resolves that phandle with `DEVICE_DT_GET`, so no
source file names the controller.

The application you ran in 1.4 takes the camera as a Zephyr device:

```c
const struct device *cam = DEVICE_DT_GET(DT_ALIAS(camera0));
struct ospi_camera_capture f;
const char *stage, *detail;
ospi_camera_take_photo(cam, frame, sizeof frame, &f, &stage, &detail);
```

The driver is not part of Zephyr. It is an out-of-tree module: a directory holding a
`Kconfig` and a `CMakeLists.txt` that the application names before the build starts.
Nothing in `boards/` and nothing in the Zephyr tree changed to add it.

<details>
<summary>How the sensor and buttons use the hardware description</summary>

The sensor uses I2C address `0x24` on the controller it shares with the OLED at `0x3c`.
The driver reaches the sensor through that controller, and the sensor's control port has
no node of its own.

The board declares four buttons as `gpio-keys` with aliases `sw0` to `sw3`. An
application can use `GPIO_DT_SPEC_GET(DT_ALIAS(sw0), gpios)` to obtain BTN0's pin and
polarity from the devicetree. BTN0 uses pin 6. Kconfig controls whether the build
includes the `gpio-keys` input driver.

</details>

The next cell reads the generated `.config` file. It prints the I2C, GPIO, display, input
and camera options this build set, the devicetree symbols behind them, and the options it
left unset.""")
code('''lab.sh("grep -E '^(CONFIG|# CONFIG)_(I2C|I2C_SIFIVE|GPIO|GPIO_SIFIVE|DISPLAY|INPUT|"
       "SSD1306|OSPI_HM01B0|DT_HAS_SIFIVE_I2C0_ENABLED|DT_HAS_SOLOMON_SSD1306FB_ENABLED|"
       "DT_HAS_UCBBAR_OSPI_HM01B0_ENABLED)[ =]' "
       "~/out/cam_capture/zephyr/.config | sort")''')
md("Eight of these symbols are set and two are not:\n\n" + fence(
    "# CONFIG_DISPLAY is not set\n"
    "# CONFIG_INPUT is not set\n"
    "CONFIG_DT_HAS_SIFIVE_I2C0_ENABLED=y\n"
    "CONFIG_DT_HAS_SOLOMON_SSD1306FB_ENABLED=y\n"
    "CONFIG_DT_HAS_UCBBAR_OSPI_HM01B0_ENABLED=y\n"
    "CONFIG_GPIO=y\n"
    "CONFIG_GPIO_SIFIVE=y\n"
    "CONFIG_I2C=y\n"
    "CONFIG_I2C_SIFIVE=y\n"
    "CONFIG_OSPI_HM01B0=y") + """

`CONFIG_I2C` and `CONFIG_GPIO` are subsystems, and the board's `_defconfig` sets them.
`CONFIG_I2C_SIFIVE`, `CONFIG_GPIO_SIFIVE` and `CONFIG_OSPI_HM01B0` are drivers, and no
file in this checkout names any of the three: the camera sample's `prj.conf` asks for none
of them. The three `CONFIG_DT_HAS_*` lines are symbols the build generated from the
devicetree, and they are what turned the drivers on.

The board describes an OLED, its symbol is `y`, and this image still carries no display
driver. Read those three facts together and predict how Kconfig reached that result. The
next cell shows both steps of the mechanism in the files where they happen.""")

code('''lab.sh("""Z=/home/ubuntu/tut/zephyr-chipyard-sw/zephyr_ws/zephyr && \\
grep -B2 -A2 '^config DT_HAS_SIFIVE_I2C0_ENABLED' ~/out/cam_capture/Kconfig/Kconfig.dts && \\
echo "... one of $(grep -c '^config DT_HAS_' ~/out/cam_capture/Kconfig/Kconfig.dts) \\
such symbols, one per compatible" && \\
echo --- && sed -n '/^config I2C_SIFIVE/,/help/p' $Z/drivers/i2c/Kconfig.sifive && \\
echo --- && grep -nE '^menuconfig I2C$|^if I2C$|Kconfig.sifive' $Z/drivers/i2c/Kconfig""")
lab.show_camera_driver_config()''')
md("Each block is one step of the same mechanism:\n\n" + fence(
    "DT_COMPAT_SIFIVE_I2C0 := sifive,i2c0\n"
    "\n"
    "config DT_HAS_SIFIVE_I2C0_ENABLED\n"
    "\tdef_bool $(dt_compat_enabled,$(DT_COMPAT_SIFIVE_I2C0))\n"
    "\n"
    "... one of 2871 such symbols, one per compatible\n"
    "---\n"
    "config I2C_SIFIVE\n"
    '\tbool "Sifive I2C driver"\n'
    "\tdefault y\n"
    "\tdepends on DT_HAS_SIFIVE_I2C0_ENABLED\n"
    "\thelp\n"
    "---\n"
    "9:menuconfig I2C\n"
    "14:if I2C\n"
    '157:source "drivers/i2c/Kconfig.sifive"\n'
    "---\n"
    "config OSPI_HM01B0\n"
    '\tbool "HM01B0 parallel-video capture unit (ucbbar,ospi-hm01b0)"\n'
    "\tdefault y\n"
    "\tdepends on DT_HAS_UCBBAR_OSPI_HM01B0_ENABLED\n"
    "\tdepends on I2C\n"
    "\thelp") + """

**The build turns the devicetree into Kconfig symbols.** `Kconfig/Kconfig.dts` in the
build directory is generated, with one entry per compatible string Zephyr knows -- 2,871
of them in this build. `dt_compat_enabled` is true when the devicetree just compiled holds
at least one node with that compatible and `status = "okay"`. So
`DT_HAS_SIFIVE_I2C0_ENABLED` is `y` here because `i2c@10040000` is in the devicetree and
enabled, and it is `n` on a board whose devicetree declares no such controller.

**Each driver's own Kconfig depends on that symbol.** `drivers/i2c/Kconfig.sifive`
declares `I2C_SIFIVE` as `default y` with `depends on DT_HAS_SIFIVE_I2C0_ENABLED`. The
third block shows where Kconfig reads that file from: inside `if I2C`. The board's
`CONFIG_I2C=y` is what makes the driver symbol exist, and the devicetree is what makes it
`y`. Two conditions in two files, and nobody typed `CONFIG_I2C_SIFIVE`. `GPIO_SIFIVE` and
`gpio@10010000` are the same pair.

The fourth block is the camera driver, in the same shape and outside the Zephyr tree:
`default y`, `depends on DT_HAS_UCBBAR_OSPI_HM01B0_ENABLED`, and a second `depends on
I2C` because it talks to the sensor over the controller its `sensor-i2c` phandle names. A
board whose devicetree has no `ucbbar,ospi-hm01b0` node generates no such symbol, so
`CONFIG_OSPI_HM01B0` does not appear in its `.config` at all and none of this code is
linked. An application can name the module on every build without costing the boards that
carry no camera anything.

<details>
<summary>Why the display driver is absent</summary>

`CONFIG_DT_HAS_SOLOMON_SSD1306FB_ENABLED=y` says the panel has an enabled node, so the
first step made its symbol true, and `SSD1306` is `default y` depending on exactly that
symbol. But `drivers/display/Kconfig` sources the driver inside `if DISPLAY`, and
`CONFIG_DISPLAY` is not set, so Kconfig never reaches the driver symbol.
`CONFIG_INPUT is not set` keeps the button driver out the same way, on a devicetree with
four enabled `gpio-keys` nodes.

An application enables the subsystems it needs in its `prj.conf`. The display sample sets
`CONFIG_DISPLAY` there. The camera sample sets neither, so its image omits both drivers
even though the board describes both devices.

</details>""")

md("""### 1.7 Configure an application for a different target

An application can use a devicetree overlay to add or change hardware nodes for its
build. The display sample's `oled.overlay` enables the I2C controller and adds a
display at `0x3d`. The board also declares a display at `0x3c`, since the panel is
sold at either address.

The example command builds the display application with that overlay:

""" + fence(
    "west build -b chipyard_pynqz1_all_f40 samples/oled_status \\\n"
    "    -- -DBOARD_ROOT=$IISWC_ROOT \\\n"
    "       -DEXTRA_DTC_OVERLAY_FILE=$IISWC_ROOT/samples/oled_status/oled.overlay") + """

The build merges the overlay with the board definition. `EXTRA_DTC_OVERLAY_FILE` adds
to the automatically discovered overlays. `DTC_OVERLAY_FILE` overrides the automatic
overlay selection.

Zephyr also finds application overlays at `<app>/boards/<board>.overlay` and Kconfig
fragments at `<app>/boards/<board>.conf`.

#### Select a trace sink for Spike

The tracing sample's `boards/spike_riscv64.conf` configures the application for the
Spike simulator. This setting disables the trace sink that writes to DRAM:

""" + fence(
    "# Target 0, not 1: spike's sink is the file writer that emits tacit.out / tacit.log /\n"
    "# tacit.debug into the CWD. It needs no address, and there is no SiFive InclusiveCache\n"
    "# control node at 0x2010000 in the simulator -- the L2 flush the FPGA needs would take\n"
    "# a store access fault here.\n"
    "CONFIG_TACIT_MB_SINK_DMA=n") + """

Zephyr picks up this fragment for the Spike target, so the application can use the
same source with a different trace sink.

The fragment's other two settings hold the same line. Spike starts one hart, so the
fragment turns SMP off rather than waiting for a second core that never arrives. And it
restates `CONFIG_SPEED_OPTIMIZATIONS=y`, which the board's defconfig sets and Spike's does
not, so both builds compile the kernels at the same optimisation level and the two
instruction streams stay comparable.

<details>
<summary>Why the cache flush depends on the target</summary>

On the board, the trace encoder writes into DRAM. The application flushes the L2 cache
so the ARM processor can read the updated memory. The camera application makes its frame
visible by evicting L2 with a sweep through unused DRAM.

Spike writes the trace to a file and has no cache controller at `0x2010000`. Accessing
that address in the simulator causes a store access fault. The configuration fragment
selects the appropriate sink for Spike.

</details>""")

# ======================================================================================
# Unit 2
# ======================================================================================
md("""---

## Unit 2 · ModelBlaster: compile a PyTorch model for the SoC

ModelBlaster compiles a PyTorch model into C for the SoC. It converts the network into
an intermediate representation (IR), quantizes weights and activations to int8, and
selects kernels for the target hardware.

You will compile SignDetLite, a small traffic-sign detector, and follow a convolution
from the model to the SoC's `MBP.DOT8` instruction. Later sections compare scalar and
accelerated execution using recorded board measurements. The compilation exercises
run on your AWS instance.

This checkout supplies deterministic random weights (`signdet/random_weights.py`,
NumPy PCG64, seed 144). They allow you to run the compilation and arithmetic checks.
The resulting model has not learned to recognize signs.""")

md("""### 2.1 Generate the model graph and C code

Run `scripts/84_signdet_lower.sh` to generate SignDetLite's IR and C code. The script
runs `extract_graph`, `generate_skeleton`, and `generate_kernels`, then writes the
results under `out/signdet/`. Allow about five seconds.""")
code('''import json
repo = lab.repo_root()
r = lab.sh(f"cd {repo} && ./scripts/84_signdet_lower.sh", timeout=900, head=0, tail=14)
signdet = lab.Lowering.from_run(r)''')
md("""The summary lists the selected kernels and an estimated inference time:

""" + fence(
    "==> op coverage\n"
    "    conv2d_s8_pc       curated[pext]        pext_patch_dot8_pc\n"
    "    permute4_s8        curated[pext_nl]     pext_block\n"
    "    softmax_s8         curated[pext_nl]     pext_int_memo2\n"
    "    MAC 7532544   est 9.61 M cycles   est 240.2 ms @ 40 MHz  (1.2755 cycles per MAC, measured)\n"
    "    all ops curated, no reference-C fallback") + """

The `extract_graph` stage writes `ir/graph.json`. This file records tensor shapes,
quantization scales, and the order in which operators run. Use the next cell to
inspect the graph.""")
code('''lab.show_graph(signdet)''')
md("""Follow the tensor names from input `x` to output `softmax`:

""" + fence(
    "signdet_b144  int8  9 operators, 8 of them dispatched to a kernel\n"
    "input  x        [1, 3, 64, 64]\n"
    "output softmax  [64, 3]\n"
    "\n"
    "  conv1     conv2d_s8_pc          x -> relu      N=1 IC=3 IH=64 IW=64 OC=16 OH=32 OW=32 ...\n"
    "  conv2     conv2d_s8_pc       relu -> relu_1    N=1 IC=16 IH=32 IW=32 OC=32 OH=16 OW=16 ...\n"
    "  conv3     conv2d_s8_pc     relu_1 -> relu_2    N=1 IC=32 IH=16 IW=16 OC=32 OH=16 OW=16 ...\n"
    "  conv4     conv2d_s8_pc     relu_2 -> relu_3    N=1 IC=32 IH=16 IW=16 OC=64 OH=8 OW=8 ...\n"
    "  conv5     conv2d_s8_pc     relu_3 -> relu_4    N=1 IC=64 IH=8 IW=8 OC=64 OH=8 OW=8 ...\n"
    "  head      conv2d_s8_pc     relu_4 -> head      N=1 IC=64 IH=8 IW=8 OC=3 OH=8 OW=8 ...\n"
    "  permute   permute4_s8        head -> permute   d0=1 d1=3 d2=8 d3=8 p0=0 p1=2 p2=3 p3=1\n"
    "  reshape   view            permute -> reshape   n=192\n"
    "  softmax   softmax_s8      reshape -> softmax   M=64 K=3\n"
    "\n"
    "graph.json md5 70a0ac6d37a0bf99a6733f40e5e64073") + """

The graph contains nine operators and makes eight kernel calls. Which operator does
not need a kernel?

<details>
<summary>Why there are eight kernel calls</summary>

The `reshape` operator is a `view`. It changes how the existing data is interpreted
without moving the bytes, so ModelBlaster does not generate a kernel for it.

ModelBlaster also folds the ReLU operations into the convolutions' activation clamps.
This explains why `conv1` produces a tensor named `relu` even though the graph has no
separate ReLU operator.

</details>

Six operators have type `conv2d_s8_pc`, an int8 convolution with per-channel
quantization. You will inspect their kernel in 2.2.""")

md("""### 2.2 Inspect the selected convolution kernel

A kernel implements an operator for the target hardware. The `generate_kernels`
stage matches IR operators with available kernels and records its choices in
`kernel_picks.json`. Run the next cell to see where each kernel comes from, which
algorithm it uses, and which C file will be compiled.""")
code('''lab.show_kernel_choices(signdet)''')
md("""Find `conv2d_s8_pc` and the kernel named `pext_patch_dot8_pc`:

""" + fence(
    "conv2d_s8_pc   curated[pext]      pext_patch_dot8_pc\n"
    "               serves 6 of the 9 operators\n"
    "               .../out/signdet/kernels_board/pext/pext_conv2d_s8_pc_pext_patch_dot8_pc.c\n"
    "permute4_s8    curated[pext_nl]   pext_block\n"
    "               serves 1 of the 9 operators\n"
    "               .../out/signdet/kernels_board/pext_nl/pext_nl_permute4_s8_pext_block.c\n"
    "softmax_s8     curated[pext_nl]   pext_int_memo2\n"
    "               serves 1 of the 9 operators\n"
    "               .../out/signdet/kernels_board/pext_nl/pext_nl_softmax_s8_pext_int_memo2.c\n"
    "\n"
    "conv2d_s8_pc carries 7,532,544 multiply-accumulates -- every one in the graph.") + """

ModelBlaster maps PyTorch's `torch.nn.Conv2d` to `conv2d_s8_pc` in the IR. The `_pc`
suffix indicates per-channel quantization. For this target, it selected
`pext_patch_dot8_pc` for all six convolutions.

The kernel gathers the input values needed for an output pixel into a contiguous
vector and arranges the weights to match. It uses `MBP.DOT8` to multiply and sum eight
pairs of int8 values at a time.

The next cell shows the loop that accumulates four output channels at once.""")
code('''lab.show_source(signdet.picks["conv2d_s8_pc"]["path"],
                around="for (b = 0; b < quads", lines=17)''')
md("""Follow `x` through the four calls to `mb_pext_dot8`:

""" + fence(
    "281      for (b = 0; b < quads; b++) {\n"
    "282          const int8_t *w = wp + (size_t)b * G * 32;\n"
    "283          const int8_t *pp = p;\n"
    "284          int64_t a0 = bias ? bias[i + 0] : 0;\n"
    "285          int64_t a1 = bias ? bias[i + 1] : 0;\n"
    "286          int64_t a2 = bias ? bias[i + 2] : 0;\n"
    "287          int64_t a3 = bias ? bias[i + 3] : 0;\n"
    "288  \n"
    "289          for (g = 0; g < G; g++) {\n"
    "290              const int64_t x = MB_PEXT_LD8(pp);\n"
    "291              a0 += mb_pext_dot8(x, MB_PEXT_LD8(w));\n"
    "292              a1 += mb_pext_dot8(x, MB_PEXT_LD8(w + 8));\n"
    "293              a2 += mb_pext_dot8(x, MB_PEXT_LD8(w + 16));\n"
    "294              a3 += mb_pext_dot8(x, MB_PEXT_LD8(w + 24));\n"
    "295              pp += 8;\n"
    "296              w += 32;\n"
    "297          }", "c") + """

`MB_PEXT_LD8(pp)` loads eight input bytes into `x`. Each call to `mb_pext_dot8`
combines those inputs with a different set of weights and adds the result to one of
the accumulators, `a0` through `a3`.

With `MB_PEXT_HW` enabled, `mb_pext_dot8` emits one `MBP.DOT8` instruction. The next
cell shows its definition in `pext.h`.""")
code('''lab.show_source(lab.repo_file("fpga/pynq-z2/sw/pext.h"),
                around="mb_pext_dot8(", before=2, lines=8)''')
md("""The helper uses the assembler's `.insn` directive to encode `MBP.DOT8`:

""" + fence(
    "173  #if MB_PEXT_HW\n"
    "174\n"
    "175  static inline int64_t mb_pext_dot8(int64_t a, int64_t b)\n"
    "176  {\n"
    "177  \tint64_t r;\n"
    "178  \n"
    '179  \t__asm__(".insn r 0x0b, 0, 0, %0, %1, %2" : "=r"(r) : "r"(a), "r"(b));\n'
    "180  \treturn r;", "c") + """

Opcode `0x0b` belongs to RISC-V's `custom-0` space. The instruction takes two 64-bit
registers, each containing eight int8 values. It multiplies corresponding pairs and
returns the sum of the eight products.

<details>
<summary>Where to read the full implementations</summary>

The convolution kernel is in
`fpga/pynq-z2/modelblaster/kernels/pext/pext_conv2d_s8_pc_pext_patch_dot8_pc.c`.
The instruction helper is in `fpga/pynq-z2/sw/pext.h`.

</details>""")

md("""### 2.3 Compare quantization with 64 and 256 calibration frames

The convolution kernel in 2.2 accumulates products before converting its results to
int8. ModelBlaster uses one scale per activation tensor and one per output channel
for the weights.

Each convolution uses a multiplier and a shift to convert its accumulators to the
output scale. Inspect these parameters in `weights.c`, then repeat calibration with
more frames to see whether they change.""")
code('''lab.show_requant_arrays(signdet)''')
md("""The output lists the array locations and prints the two arrays for `conv1`:

""" + fence(
    "weights.c is 4,477 lines. 52 of them are the requantise grid: 12 arrays, 422 int32 values.\n"
    "\n"
    "  line    10  signdet_b144_conv1_output_multiplier_per_oc_roccmoon [16]\n"
    "  line    14  signdet_b144_conv1_output_shift_per_oc_roccmoon      [16]\n"
    "  line    53  signdet_b144_conv2_output_multiplier_per_oc_roccmoon [32]\n"
    "  ...\n"
    "  line  4460  signdet_b144_head_output_shift_per_oc_roccmoon       [3]\n"
    "\n"
    "const int32_t signdet_b144_conv1_output_multiplier_per_oc_roccmoon[16] = {\n"
    "    1591242990, 1736033205, 1084498289, 1308506831, ...\n"
    "};\n"
    "\n"
    "const int32_t signdet_b144_conv1_output_shift_per_oc_roccmoon[16] = {\n"
    "    8, 9, 8, 8, 9, 9, 8, 9, 9, 9, 8, 9, 8, 9, 9, 9,\n"
    "};") + """

Each output channel has one entry in each array. Its multiplier and shift encode the
scale ratio *M* = input scale × weight scale ÷ output scale. The next cell uses these
values to recover the weight scale for each channel.

<details>
<summary>How the kernel applies the scale</summary>

The kernel computes `(acc * multiplier + 2^30) >> 31 >> shift` using integer arithmetic.
This approximates multiplying the accumulator by *M*.

</details>""")
code('''lab.show_requant_channels(signdet)''')
md("""Compare the first two channels in the `implied weight scale` column:

""" + fence(
    "conv1   input scale 0.007874015748 (= 1/127)   output scale 0.014415336406\n"
    "\n"
    "  oc   multiplier  shift          M   implied weight scale   max |W| that fits\n"
    "   0   1591242990      8   0.00289445         0.00529902   0.672975\n"
    "   1   1736033205      9   0.00157891         0.00289059   0.367105\n"
    "   2   1084498289      8   0.00197269         0.00361150   0.458660\n"
    "   3   1308506831      8   0.00238016         0.00435747   0.553399\n"
    "\n"
    "  ... and 12 more channels. Every channel saturates at 127, which is what per-channel\n"
    "  means: the multiplier absorbs the range, not the weights.") + """

Channel 0's scale covers weight magnitudes up to about 0.673, and channel 1's covers
up to about 0.367. The separate scales let both channels use the available int8 range.

#### Recalibrate with more frames

ModelBlaster runs calibration frames through the float model to estimate activation ranges.
The earlier build used 64 frames. Run the next cell to lower the same checkpoint with
256 frames and compare the generated arrays.

Predict which values will change when you use more calibration frames: the quantized
weights, the multipliers, or the shifts.""")
code('''r256 = lab.sh(f"cd {repo} && ./scripts/84_signdet_lower.sh --name signdet_cal256 --ncal 256",
              timeout=900, quiet=True)
lab.compare_calibration(signdet, lab.Lowering.from_run(r256))''')
md("""Read the `differ` column to see how many entries changed in each array:

""" + fence(
    "graph.json md5   64 frames 70a0ac6d37a0bf99a6733f40e5e64073\n"
    "                256 frames 5e3ac0705fe5ef1beb7a35afc2b15138\n"
    "\n"
    "array                               entries   differ\n"
    "conv1.output_multiplier_per_oc           16       16\n"
    "conv1.output_shift_per_oc                16        3\n"
    "conv2.output_multiplier_per_oc           32       32\n"
    "conv2.output_shift_per_oc                32        1\n"
    "conv3.output_multiplier_per_oc           32       32\n"
    "conv3.output_shift_per_oc                32        0\n"
    "conv4.output_multiplier_per_oc           64       64\n"
    "conv4.output_shift_per_oc                64       20\n"
    "conv5.output_multiplier_per_oc           64       64\n"
    "conv5.output_shift_per_oc                64        4\n"
    "head.output_multiplier_per_oc             3        3\n"
    "head.output_shift_per_oc                  3        1\n"
    "\n"
    "weight_q arrays identical: True") + """

The final line confirms that the weights are identical. Every multiplier changes, while
only some shifts change. Compare these results with your prediction.

<details>
<summary>Why the scaling parameters change</summary>

ModelBlaster derives weight scales from the checkpoint's weights, which stayed the
same in this comparison. It estimates activation scales from the calibration frames.
Changing those frames can change the output rescaling even when the weights stay
fixed.

Record the calibration count with the generated model. The two runs above have
different `graph.json` hashes.

</details>""")

md("""### 2.4 Compile the model with scalar kernels

Compile the same model again with `--scalar`. This option selects ModelBlaster's
reference C kernels for every dispatched operator. The next cell compares the result
with the accelerated build. Allow about five seconds.""")
code('''rs = lab.sh(f"cd {repo} && ./scripts/84_signdet_lower.sh --name signdet_scalar --scalar",
            timeout=900, head=0, tail=8)
scalar = lab.Lowering.from_run(rs)
lab.compare_backends(signdet, scalar)''')
md("""Compare the selected kernels and the hashes of the generated files:

""" + fence(
    "conv2d_s8_pc   pext    curated[pext]      pext_patch_dot8_pc\n"
    "               scalar  reference          None\n"
    "permute4_s8    pext    curated[pext_nl]   pext_block\n"
    "               scalar  reference          None\n"
    "softmax_s8     pext    curated[pext_nl]   pext_int_memo2\n"
    "               scalar  reference          None\n"
    "\n"
    "ir/graph.json    same   70a0ac6d37a0bf99a6733f40e5e64073  70a0ac6d37a0bf99a6733f40e5e64073\n"
    "gen/weights.c    same   e706082b34c472af1e9ad072eb5b88b4  e706082b34c472af1e9ad072eb5b88b4\n"
    "gen/kernels.c    differs   19d585027f49cc808b2b0339e2dfaf24  3c9bcaf92dec52668773cfaf41045209\n"
    "\n"
    "kernels.c    1382 lines on pext,  119 on scalar") + """

The graph, weights, and quantization parameters are identical in this comparison.
The kernel implementations change. The next cell shows the scalar convolution's
inner loops.""")
code('''lab.show_source(scalar.gen / "kernels.c", around="acc +=", before=11, lines=16)''')
md("""Find the line that multiplies an input value by a weight and adds it to `acc`:

""" + fence(
    " 25                  for (int ow = 0; ow < OW; ow++) {\n"
    " 26                      int32_t acc = bias ? bias[oc] : 0;\n"
    " 27                      for (int ic = 0; ic < IC; ic++) {\n"
    " 28                          for (int kh = 0; kh < KH; kh++) {\n"
    " 29                              int ih = oh * SH - PH + kh;\n"
    " 30                              if (ih < 0 || ih >= IH) continue;\n"
    " 31                              for (int kw = 0; kw < KW; kw++) {\n"
    " 32                                  int iw = ow * SW - PW + kw;\n"
    " 33                                  if (iw < 0 || iw >= IW) continue;\n"
    " 34                                  int32_t iv = "
    "(int32_t)input[((n*IC + ic)*IH + ih)*IW + iw] + input_offset;\n"
    " 35                                  int32_t wv = "
    "(int32_t)weight[((oc*IC + ic)*KH + kh)*KW + kw] + filter_offset;\n"
    " 36                                  acc += iv * wv;\n"
    " 37                              }\n"
    " 38                          }\n"
    " 39                      }\n"
    " 40                      int64_t prod = ((int64_t)acc * (int64_t)mult + (1LL << 30)) >> 31;",
    "c") + """

The scalar loop performs one multiply-accumulate with `acc += iv * wv`. The accelerated
kernel uses `mb_pext_dot8` to accumulate eight products per call. Both apply the same
output rescaling after accumulation.

<details>
<summary>Where to compare the source files</summary>

The generated scalar kernel is in `out/signdet_scalar/gen/kernels.c`.
The accelerated kernel is in
`fpga/pynq-z2/modelblaster/kernels/pext/pext_conv2d_s8_pc_pext_patch_dot8_pc.c`.

</details>""")

md("""### 2.5 Compare recorded board runs

The next cells read recorded results from `assets/signdet_board_cycles.json`. The
scalar and accelerated images used the same graph, trained checkpoint, and input
frame. The earlier compilation exercises use the random weights in the public checkout.

Both images were built with `scripts/86_signdet_board.sh` and run on a PYNQ-Z1 with
bitstream `0x5A5A0038` at 40 MHz. The test harness records a cycle count for each
operator dispatch and compares all 192 output bytes against a reference computed on
the host.

The harness also deliberately executes `MBP.DOT8` on hart 1, which does not support
the instruction. This test expects an illegal-instruction trap. Run the next cell
to inspect the accelerated run.""")
code('''board = json.load(open("assets/signdet_board_cycles.json"))
lab.show_board_provenance(board)''')
md("""Look for `max_abs_err=0` and the expected illegal-instruction trap in the console:

""" + fence(
    "MB_PEXT_BUILD model=signdet_b144 quant=int8 ops=8 iters=11 hw=1\n"
    "MB_PEXT_RUN cpu=0 mhartid=0 median=9508851 min=9504987 max=9514870 warm=9519734 "
    "mtime=9505 max_abs_err=0\n"
    "MB_PEXT_OP id=0 name=conv1 op=conv2d_s8_pc shape=N=1;IC=3;IH=64;... cycles=998077\n"
    "MB_PEXT_OP id=1 name=conv2 op=conv2d_s8_pc shape=N=1;IC=16;IH=32;... cycles=1197067\n"
    "...\n"
    "MB_PEXT_OP id=7 name=softmax op=softmax_s8 shape=M=64;K=3 cycles=51859\n"
    "   hart 0 (big): median 237.721 ms   max_abs_err=0\n"
    "MB_PEXT_NEG starting -- one MBP.DOT8 pinned to CPU 1; an illegal-instruction trap "
    "here is the PASS\n"
    "\n"
    " mcause: 2, Illegal instruction\n"
    "  mtval: d7070b\n"
    "...\n"
    "   hart 1 refused 0x00d7070b -- custom-0, funct3=0: MBP is on hart 0 only, as specified\n"
    "RESULT: PASS -- the MBP kernels ran bit-exact on hart 0 and the same instruction is "
    "illegal on hart 1") + """

`median` gives the cycle count for one inference, measured across eleven inferences
after a warm-up. The `MB_PEXT_OP` lines report operator cycle counts from the same run.
The next cell compares the two backends.""")
code('''lab.show_board_arms(board)''')
md("""Compare the `frame` totals, then check that both outputs match the reference:

""" + fence(
    "                           MBP kernels    reference C   factor\n"
    "conv1    conv2d_s8_pc          998,077     10,687,289   10.71x\n"
    "conv2    conv2d_s8_pc        1,197,067     26,614,336   22.23x\n"
    "conv3    conv2d_s8_pc        2,764,055     50,937,793   18.43x\n"
    "conv4    conv2d_s8_pc        1,322,570     25,645,999   19.39x\n"
    "conv5    conv2d_s8_pc        3,080,706     48,684,531   15.80x\n"
    "head     conv2d_s8_pc           86,788        454,883    5.24x\n"
    "permute  permute4_s8             2,117          9,697    4.58x\n"
    "softmax  softmax_s8             51,859        889,603   17.15x\n"
    "frame                        9,508,851    163,923,052   17.24x\n"
    "ms at 40 MHz                    237.72       4,098.08\n"
    "\n"
    "pext           custom-0 instructions in the binary  49   output vs golden: 0 of 192 "
    "bytes differ, max |d| = 0\n"
    "scalar         custom-0 instructions in the binary   1   output vs golden: 0 of 192 "
    "bytes differ, max |d| = 0") + """

The accelerated image completes inference 17.24 times faster in this measurement.
Both images match all 192 reference output bytes.

The scalar image contains one custom-0 instruction for the deliberate test on hart 1.
Its kernels use the reference C implementations.

The figure compares total inference time in the upper panel and each operator's share
of its backend's total in the lower panel.""")
code("lab.kernel_speedup_figure(board)")
md("""The five 3x3 convolutions account for 98.46% of the accelerated inference and 99.17%
of the scalar inference. They remain the largest part of runtime on both backends.

`conv1` accelerates by 10.71x, while `conv2` accelerates by 22.23x. As a result,
`conv1`'s share grows from 6.52% of the scalar inference to 10.50% of the accelerated
inference.

<details>
<summary>How layer shape affects the comparison</summary>

The first convolution has three input channels and a 3x3 filter, so each input patch
contains 27 values. The kernel pads the patch for `MBP.DOT8`, which processes eight
int8 values at a time. Later convolutions use 16, 32, or 64 input channels, which fit
into groups of eight. Padding and setup work can limit how much of the instruction's
throughput a kernel uses.

`head` and `permute` improve by 5.24x and 4.58x. Their accelerated cycle counts,
86,788 and 2,117, represent 0.91% and 0.02% of the total. For such small dispatches,
setup work can be a substantial share of execution.

</details>""")

md("""### 2.6 Compare detector and speech workloads

SignDetLite runs the same eight operator dispatches for each 64x64x3 image and
produces an 8x8x3 output grid. Its computation has a fixed shape.

Moonshine transcribes a four-second audio window in two stages. Its encoder produces
165 hidden states of 288 values each. Its decoder generates one token per step and
stops when it emits end-of-sequence. This build allows up to 24 steps.

In the matrix multiplications summarized below, the encoder processes 165 rows
together, and the decoder processes one row per token. This gives the encoder more
opportunities to reuse each weight load.

The next cell compares model sizes, operator counts, and the arithmetic performed
per byte of weight data using the supplied measurement record.""")
code('''lab.show_model_shapes()''')
md("Compare the dispatch counts and the decoder's arithmetic per byte of weight data:\n\n" + fence(
    "SignDetLite runs once per camera frame.\n"
    "  8 dispatches, 7,532,544 multiply-accumulates,\n"
    "  9,511,271 cycles = 238 ms at 40 MHz,\n"
    "  72,276 bytes of weights.\n"
    "\n"
    "Moonshine Tiny runs encoder once per four-second window, then the decoder once per "
    "output token.\n"
    "  encoder    117 dispatches, every matrix multiply 165 rows tall\n"
    "  prologue    12 dispatches, also 165 rows tall\n"
    "  decoder    176 dispatches per step, every matrix multiply 1 row tall\n"
    "            164 at the first step: there is no cache to append to yet\n"
    "\n"
    "  18,993,024 multiply-accumulates per token against 18,395,136 weight bytes\n"
    "  = 1.03 multiply-accumulates per byte of weight read.\n"
    "  The encoder does 165 rows of arithmetic on the same weights; the decoder does one.\n"
    "\n"
    "  Self-attention reads 1 key at the first step and 24 at the last.\n"
    "  The model stops when it emits end-of-sequence, on average after 11.25 of the 24 "
    "steps that are compiled in.\n"
    "\n"
    "  About 2,098 dispatches for one utterance, against 8 for one frame of the detector."))
md("""The decoder performs about 1.03 multiply-accumulates per byte of weight data read.
The encoder's larger matrices reuse weights across 165 rows. These shapes help explain
why memory traffic matters to the decoder's performance.

In Unit 5, you will schedule four SignDetLite inferences at one-second intervals
alongside a Moonshine job. The detector provides periodic work with a fixed graph.
The speech job's total work depends on the number of decoded tokens.

<details>
<summary>How later decoding steps add work</summary>

The decoder attends to the tokens it has already generated. The first step reads one
key, and the 24th reads 24. The lowering unrolls all 24 steps into code and extends
the key and value cache using concatenation. These operations add work to later steps.

The first step dispatches 164 operators. Later steps dispatch 176 because they also
append to the cache. In the recorded workload, the model stops after an average of
11.25 steps, for about 2,098 dispatches per utterance.

</details>

<details>
<summary>How a lookup table speeds up GELU</summary>

Moonshine's encoder evaluates the GELU activation 1,378,656 times per utterance. The
activation appears twice in the convolutional stem and once in each of the six
encoder layers.

With fixed per-tensor symmetric quantization scales, each possible input byte maps
to a fixed output byte. A 256-entry table can precompute this mapping from the
reference expression.

The recorded benchmarks report a 167.48x speedup over the float version for the GELU
pass in a transformer feed-forward block and a 153.09x speedup for a model dispatch.
The whole block improved by 4.72x. The table matched the reference output on every
checked row and uses ordinary instructions to look up each result.

</details>

<details>
<summary>How model weights affect image updates</summary>

The image carrying both models is 67.0 MB: 1.1 MB of code and 65.9 MB of read-only data.

A recorded kernel update modified 15 KB of code. That gave every weight a new address
without changing any weight's contents, so 65.5 MB of weight symbols are identical and
merely relocated. A delta that re-anchors after the shift is 257 KB, 260 times smaller than
sending the image again. A 4 KB block diff over the same two images re-anchors on nothing:
it calls 99.8% of the blocks changed and saves nothing at all.

</details>

<details>
<summary>Which weights the tutorial supplies</summary>

Moonshine uses a public checkpoint pinned to one revision. The download requires no
account or licence-acceptance step, and the tutorial checks each file against a
recorded SHA256 hash.

The trained SignDetLite checkpoint uses the German Traffic Sign Detection Benchmark.
The tutorial omits that checkpoint because its redistribution terms were unresolved
when the material was prepared. The public checkout uses the deterministic random
weights introduced at the start of this unit for the compilation exercises.

</details>""")

# ======================================================================================
# Unit 3
# ======================================================================================
md("""---

## Unit 3 · TACIT: trace execution on both cores

TACIT's hardware encoders record instruction execution in memory. A decoder converts
the trace into a timeline of function calls.

You will inspect a supplied trace, then capture execution on both cores of your board
and download the files. The tutorial identifies the SoC's two hardware threads as
hart 0 and hart 1.

The timeline exercises use captures decoded in advance. Decoding takes about eight
minutes and requires a decoder that is not installed on your instance.""")

md("""### 3.1 Open Perfetto

Open Perfetto on your laptop and wait for the page to finish loading:

<https://ui.perfetto.dev>

Look for **Open trace file** in the left sidebar. Keep the tab open so you can use it
if the internet connection drops. The first load requires internet access, and the
room has no offline copy of the viewer.

""" + fixes_table([
    ("Perfetto cannot load because the internet connection is down.", "Follow along with a neighbour who has the viewer open, or watch the instructor's demonstration."),
]))

md("""### 3.2 Inspect a supplied trace

Inspect a trace of a field-oriented control loop supplied with the notebook. The
next cell unpacks it into `rocket_tacit_trace.perfetto.json`.""")
code("t = lab.unpack_trace()")
md("""This trace was captured on a Rocket SoC on 2026-09-16. It contains 534,990 decoded
instructions, recorded at 2.021 bits per instruction. The unpacked timeline is about
1.99 MB.

The next cell ranks functions by their own trace ticks, excluding time spent in
functions they call.""")
code("lab.trace_summary(t)")
md("""Read the `self ticks` and `share` columns to identify the busiest functions:

""" + fence(
    "function                    self ticks   share    calls\n"
    "__muldf3                       210,583   31.3%    1,515\n"
    "__subdf3                        99,067   14.7%    1,146\n"
    "__mulsf3                        56,400    8.4%      600") + """

Six of the eight busiest functions are compiler routines for floating-point arithmetic:
`__muldf3`, `__subdf3`, `__mulsf3`, `__addsf3`, `__subsf3`, and `__adddf3`. The core has
no floating-point unit, so it implements the control loop's `float` and `double`
operations in software. These routines account for much of the recorded execution time.

You can open the timeline in either of two ways.

To use the Perfetto tab you opened in 3.1, right-click `rocket_tacit_trace.perfetto.json`
in JupyterLab's file browser and choose **Download**. Drag the downloaded file into that
tab.

To stay in the notebook, run the next cell instead. It puts the viewer in a frame below
the cell and hands it the trace directly, so no file is saved on your laptop. The frame
loads the viewer from the same site, so it needs the same internet connection.""")
code('''lab.show_perfetto(t)''')
md("""The viewer reports its progress above the embedded timeline:

""" + fence(
    "fetch -> HTTP 200\n"
    "trace in the page: 1989396 bytes\n"
    "viewer loaded\n"
    "handed to the viewer -- answer Yes in the frame below") + """

When Perfetto asks whether this notebook may open the file, choose **Yes**.""")

md("""### 3.3 Compare trace start points

The point where you enable tracing determines which part of execution you record.
The two recorded runs below perform the same application work. One starts tracing at
reset, and the other starts at `main()`. Compare their first events and the cycles
recorded before `main()`.

| Measurement | Trace starts at reset | Trace starts in `main()` |
|---|---|---|
| Work counted by the application | **24,093** | **24,093** |
| Cycles while the encoder was enabled | 1,636,333 | 679,794 |
| Cycles before `main()` | **958,012 (58.5 %)** | 0 |
| Trace bytes | 147,093 | 135,182 |
| Timeline events | 10,064 | 9,839 |
| Distinct function names | **93** | **42** |
| First event | **`z_prep_c`** | **`__floatsidf`** |

The reset capture includes 958,012 cycles before `main()`, or 58.5% of its recorded
window. Its first function, `z_prep_c`, clears the BSS during boot. The capture started
at `main()` begins in `__floatsidf`, the compiler's integer-to-double helper.

Why are the trace sizes so close when the recorded cycle counts differ so much?

<details>
<summary>How compression affects trace size</summary>

The two captures differ by 8.8% in bytes and 2.3% in timeline events. Their five
busiest functions appear in the same order. The encoder compresses control flow, so
long stretches of straight-line boot code can occupy relatively few trace bytes.

Check the first event to establish where a capture begins. In these runs, the number
of distinct function names also helps identify whether boot was included: 93 from
reset and 42 from `main()`.

</details>""")

md("""### 3.4 Capture both harts on your board

This application runs SignDetLite on hart 0 and a wake-word model on hart 1. It
enables both trace encoders from reset and stops them at a shared deadline about
13 seconds later.

Hart 0 supports the packed-SIMD instructions used by SignDetLite. Hart 1 runs scalar
code. The shared window lets you compare when each core performs model work.

Build the capture application with the next cell. It includes both models and takes
a few minutes to build.""")
code('''build = lab.sh("""cd /home/ubuntu/tut && source /home/ubuntu/tut/env.sh && \\
./scripts/90_b156_tacit_window.sh --name lab3 --build-only""", timeout=1800)
if not build.ok:
    raise RuntimeError("the build failed -- read the log above before going on")''')
md("""Look for `lab3_duo: bin=1096544 B  window_ms=13000 frames=0 kws_s=60` at the end of
the build.

The next cell uploads the application, selects the `trace` bitstream, and starts the
capture. This configuration includes the trace encoders and omits the dispatch engine.
After downloading the capture, complete the restoration step below to reload the
`all` bitstream before using the board again.""")
code('''lab.board_put("/home/ubuntu/tut/out/lab3_duo/zephyr.bin", "tacit.bin")
lab.board("bitstream", "trace")
lab.board("run", "tacit", timeout=300)''')
md("""In the recorded run, the 1,096,544-byte upload took about eight seconds. Loading
the bitstream took fourteen seconds, and the run operation took seventy-five.
The next cell reads the console and prints the capture checks.""")
code('''c = lab.board("get", "console.out", binary=True, verbose=False)
lab.show_console_lines(lab.console_text(c), "DUO_TRACE_ARM", "DUO_TRACE_HART",
                       "DUO_TRACE_GATE", "SD_REPLAY_END", "DUO_DONE")''')
md("""Card 3 reported the following capture. Compare `DUO_TRACE_GATE` and `DUO_DONE`
with your result:

""" + fence(
    "DUO_TRACE_ARM hart=0 from_reset=1 buf=0x81000000 addr_rb=0x81000000 span=67108864 "
    "count_at_main=170040 ok=1\n"
    "DUO_TRACE_ARM hart=1 from_reset=1 buf=0x85000000 addr_rb=0x85000000 span=150994944 "
    "count_at_main=93040 ok=1\n"
    "SD_REPLAY_END decisions_ok=1 tensors_ok=1 thr_match=1\n"
    "DUO_TRACE_HART hart=0 buf=0x81000000 bytes=23596344 span_cycles=534655340 "
    "bytes_per_s=1765349 buf_span=67108864 full_pct=35 armed=1 ...\n"
    "DUO_TRACE_HART hart=1 buf=0x85000000 bytes=15962636 span_cycles=534655340 "
    "bytes_per_s=1194237 buf_span=150994944 full_pct=10 armed=1 ...\n"
    "DUO_TRACE_GATE overrun=0 overlap=0 base0=0x81000000 end0=0x82680d38 base1=0x85000000 "
    "end1=0x85f3920c\n"
    "DUO_DONE want=2 got=2 sign=1 kws=1") + """

Check for `overrun=0 overlap=0` in `DUO_TRACE_GATE` before using the capture. These
fields report whether the trace data stayed within its allocated regions and whether
the two regions overlap. Ask an instructor if either value is nonzero.

The `DUO_DONE` line reports whether both harts finished. In this run,
`count_at_main=170040` shows that hart 0 had already written 170,040 trace bytes when
it entered `main()`.

Your byte counts may differ because the amount of work completed within the timed
window varies between runs.

<details>
<summary>Why the trace buffers need explicit checks</summary>

The trace sink writes sequentially from its base address. It has no limit register
and keeps writing when its allocated region fills. If one hart writes beyond its
region, it can overwrite the other hart's trace.

The application checks the written ranges against the allocated regions. An
overwritten trace may still decode, so the buffer checks are needed before interpreting
the result.

</details>

The next cell reads both traces from board memory. The `drain` operation uses the
addresses and lengths reported by the board and compresses the files before transfer.
The recorded capture compressed from about 39 MB to 3 MB.""")
code('''d = lab.board("drain", timeout=900, verbose=False)
lab.fetch_drained_lanes(d)''')
md("""Allow about a minute for the download. Check that each file's size matches the
size declared by the board:

""" + fence(
    "2 lanes, 39,558,980 bytes of trace, 3,148,637 bytes compressed\n"
    "  hart 0: tacit0.out.gz, 2,604,891 B (the card declared 2,604,891)\n"
    "  hart 1: tacit1.out.gz, 543,746 B (the card declared 543,746)") + """

The downloaded `tacit0.out.gz` and `tacit1.out.gz` contain your capture. You will
decode them below.

**Restore the board before continuing.** Decoding needs only your instance, so the board
is free from here on. Run the next cell to reload the `all`
bitstream and restart `boot_info`.""")
code('''lab.board("bitstream", "all")
lab.board("run", "boot_info", timeout=300)''')
md("""Check that the responses include `\"loaded\": \"all\"` and `\"ran\": \"boot_info\"`.
The loader checks the FPGA configuration, and the run log should contain:

""" + fence("MAGIC = 0x5A5A0038 OK") + """

The OLED's uptime counter should restart at `up 0:00`.""")

md("""### 3.5 Decode your capture

The encoders wrote compressed instruction deltas, not function names. Only the decoder
can turn those back into a timeline, and it needs the same binary the board ran: given a
different build it reports a mismatch rather than inventing names.

Decoding about 30 MB takes five to eight minutes. Start the next cell and read on.""")
code('''summary = lab.decode_capture(["tacit0.out.gz", "tacit1.out.gz"],
                            "/home/ubuntu/tut/out/lab3_duo/zephyr.elf")
lab.show_decode_check(summary)''')
md("""The check prints the two fields that separate a real decode from an empty one:

""" + fence(
    "lane 0: 81,465 events, 178 distinct function names\n"
    "  first  z_prep_c\n"
    "lane 1: 50,342 events, 103 distinct function names\n"
    "  first  boot_secondary_core") + """

A decoder that never finds a synchronisation point still exits successfully and still
writes a file, so file size proves nothing. The number of **distinct** function names does:
a lane carrying one repeated name did not decode. Hart 0 begins in `z_prep_c`, the boot
code that clears memory, and hart 1 in `boot_secondary_core`, where the second core starts.

Decoding writes `lane_timeline.json` beside your notebook, which the next section reads.

### 3.6 Compare both cores on a shared timeline

Each lane represents one core of your capture. The next cell summarizes the work
recorded on each lane. If you skipped the decode, it falls back to a supplied capture.""")
code('''lanes = lab.lane_table()
lab.show_lane_table(lanes)''')
md("""Compare how much of the capture window each hart spends in model functions:

""" + fence(
    "pid 0  0\n"
    "    148,268 events, 179 distinct frames\n"
    "    in the model  16.9% of the window, spin/console/idle  78.0%\n"
    "pid 1  1\n"
    "     67,371 events, 103 distinct frames\n"
    "    in the model  74.4% of the window, spin/console/idle  19.5%\n\n"
    "model work on the two lanes ends 0.35 s apart = 2.6% of the window\n"
    "checks: busy_ok pass, ends_together_ok pass -- 0 failures") + """

Your percentages will differ from these. Both harts share one wall clock, so what to read
is the SHAPE rather than the numbers: hart 0 spends most of the window idle, because
SignDetLite finishes a frame and waits, while hart 1 stays inside the model almost the
whole time. The two checks say whether each lane recorded real model work and whether the
two stopped together.

The two figures do not sum to 100%: the rest is work that is neither the model nor idle --
driving the display, the I2C bus, the console. Idle here means the scheduler's idle frame
with no model frame inside it, which is why it can be read next to the model share at all.
The next cell plots model activity over time.""")
code("lab.lane_timeline_figure(lanes)")
md("""Each point shows the fraction of a time bucket spent inside an `mb_pext_conv` call.
Both lanes contain model work in every bucket after startup. The dashed lines mark
the end of the last such call on each hart.

<details>
<summary>Estimate buffer requirements from an active capture</summary>

A busy hart 0 produced 0.0443 bytes per core cycle, or 1.77 MB/s. In a separate run
where it was idle for 80% of the window, its average rate was 0.0084 bytes per core
cycle, about five times lower.

A spin loop produces relatively little trace data, so idle periods lower the average
rate. Use a recording in which the core stays busy to estimate the buffer size for
your planned capture.

</details>""")

# ======================================================================================
# Units 4 and 5
# ======================================================================================
md("""---

## Unit 4 · Optimize a kernel with a language model

Unit 2 used kernels written by hand. In this unit, you will use ModelBlaster to ask a
language model to rewrite `maxpool2d_s8`, then check its correctness and measure its
speed on your board.

The reference kernel compares signed 8-bit values one pair at a time. The board's
`MBP.MAX8` instruction compares eight pairs at once. The model's task is to arrange the
values in packed registers so the loop can use that instruction.""")

md("""### 4.1 Follow the optimization loop

ModelBlaster asks the model for candidate kernels and evaluates them in Spike, a
RISC-V simulator. It ranks the candidates by simulated cycle count. The supplied
Spike build supports the board's MBP instructions, including `MBP.MAX8`.

After the first round, the optimizer builds the best candidate for your FPGA and
measures it on the board. It adds those measurements to the model's prompt for the
second round.

Spike counts each instruction as one cycle and omits memory timing. The board
measurements give the model feedback about costs that Spike cannot represent,
including memory access delays.

<details>
<summary>How the run checks correctness</summary>

The run uses three checks:

- ModelBlaster verifies each candidate on the host using five shapes with random inputs.
  An eight-byte load from an unaligned address traps there, as it does on the board.
- Spike runs the kernel on a test tensor and compares its output with the expected values.
- A negative control executes a `custom-0` instruction on hart 1, where MBP is unavailable.
  That instruction must trap, confirming that the core rejects it.

The run requires these checks to pass before accepting a result.

</details>

<details>
<summary>What the model is told about MBP</summary>

ModelBlaster describes each hardware target to the model with an optimization guide and
the headers its kernels can use. For RVV, that is a guide to the vector instructions and
`<riscv_vector.h>`. For this board, the guide describes the four MBP instructions, the
alignment rule, and the patterns that use them, and `pext.h` provides the instructions.
The model decides what each candidate tries.

</details>""")

md("""### 4.2 See what MBP.MAX8 computes

`MBP.MAX8` treats two 64-bit registers as eight signed 8-bit lanes and keeps the larger
value in each lane. A 2×2 max pool uses it twice: once across two input rows, and once
across neighbouring columns after shifting the result by one lane.""")
code('''lab.show_max8(seed=7)''')
md("""Check that the four outputs match the reference kernel's. In the figure, the orange
lanes of the last row are those outputs.""")

md("""### 4.3 Check the optimizer setup

The next cell checks for five required files: the model credentials, the development
environment settings, the Spike build with MBP support, the optimizer script, and the
key your instance uses to reach the board.""")
code('''ready = lab.mb_preflight()''')
md("""Check that all five lines say `yes`. If any says `NO`, the next cell skips the
optimization and reads a run recorded on a real board instead. Ask the instructor for
help with the missing setup.""")

md("""### 4.4 Run the search

The next cell requests two rounds of optimization for `maxpool2d_s8` and limits the
search to eight model calls with `max_calls=8`. The search can stop early if a round
finds no improvement.""")
code('''run = lab.mb_optimize(ready, "maxpool2d_s8", rounds=2, beam=2, expansions=2, max_calls=8)''')
md("""Allow several minutes for the run to finish. The line under the cell shows the current
step, and the chart below it redraws as the candidates are scored. Building and
simulating the candidates accounts for much of that time.

Check the path after `run:` to see which run the remaining cells will inspect.

<details>
<summary>If the model or the board does not answer</summary>

If the model does not answer, the run replays a kernel the model wrote in an earlier
run. If the board does not answer, the run measures on Spike only. The cell prints
which fallback it used.

</details>""")

md("""### 4.5 Inspect the model calls

The `beam`, `expansions`, and `rounds` settings control how many candidates the
search can explore. Read the call log below to see how many calls it actually made.
The table gives each call's round, phase, input and output token counts, time in
seconds, and what the candidate tried.""")
code('''lab.show_search_shape(run)''')
md("""The `phase` column distinguishes `synth` calls, which request an initial kernel,
from `optimize` calls, which request improvements.

Compare the `in` column between rounds. The prompt includes board measurements once
they are available, so later calls may use more input tokens.""")
code('''lab.show_model_inputs(run)''')
md("""Check that every call used the MBP optimization guide, and that the board's numbers
appear from round 2. Open a call below the lines to read its prompt and the model's
answer.""")

md("""### 4.6 Read the board feedback

The optimizer writes the board measurements to a feedback file and adds them to the
next round's system prompt. Read the file below to see what information the model
receives.""")
code('''lab.show_board_feedback(run)''')
md("""Find the cycles per output for the reference kernel and the previous round's
candidate, measured on the FPGA at 40 MHz. The feedback also explains that Spike
omits memory timing.

<details>
<summary>Give the model more detailed feedback with TACIT</summary>

You could extend the search to include a TACIT trace from Unit 3. The model would
then see which functions ran and how execution moved through them, alongside the
board's cycle totals.

</details>""")

md("""### 4.7 Inspect the generated kernel

The next cell shows the loop that uses MBP from the kernel the search kept. The lines
marked `>>` use it.""")
code('''lab.show_llm_kernel(run)''')
md("""The recorded kernel loads eight bytes at a time into a register and calls
`mb_pext_max8` to compare the packed values. Your generated kernel may differ.
Follow one loop iteration to see which input values it compares and which outputs
it writes.""")
code('''lab.show_on_accelerator(run)''')
md("""Check that the kernel contains `MBP.MAX8`, that the same instruction trapped on hart 1,
and that no MBP instruction is left in the build with MBP disabled.""")

md("""### 4.8 Compare the board results

The board runs three builds with the same input data:

| Row | Kernel |
|---|---|
| `before` | The reference kernel. |
| `after` | The generated kernel using MBP instructions. |
| `mbpoff` | The generated kernel built with `-DMB_PEXT_HW=0`. |""")
code('''lab.show_board_verdict(run)''')
md("""Check that all three rows report `bit-exact`, then compare their cycles per output.
Lower values mean the kernel finished faster.

With `-DMB_PEXT_HW=0`, the kernel keeps its packed eight-byte loads and executes a C
implementation of `mb_pext_max8`. Comparing `mbpoff` with `after` measures the benefit
of using the hardware instruction within that packed loop.

<details>
<summary>Interpret the speedup ratios</summary>

The recorded ratios were about 1.7× from `before` to `mbpoff`, 10.5× from `mbpoff` to
`after`, and 17.6× overall. The first comparison measures the combined effect of
packed loads and software SIMD emulation. It cannot isolate the loop rewrite's
contribution.

A separate bench experiment disabled the MBP path entirely. That version ran
**three percent slower than the reference**. For this kernel, the loop rewrite
makes `MBP.MAX8` usable, and the instruction provides most of the measured speedup.

</details>""")
code('''lab.optimizer_figure(run)''')
md("""The chart shows every candidate the search tried: blue bars are Spike, orange bars
are your board, and the dashed outline is the same kernel with MBP disabled. Compare
the gap between Spike and the board for the reference and for the generated kernel.""")

md("""### 4.9 Optional: write the kernel yourself

Try writing the MBP kernel by hand. Each attempt takes about two minutes on the board,
and the rest of the tutorial does not depend on this step.

The next cell copies the reference kernel to a file you can edit. The comment at the
top of the file gives the rules and four hints.""")
code('''kernel = lab.mb_start("maxpool2d_s8")''')
md("""Open the file in the file browser, edit it, and save it. The next cell checks your
kernel on Spike first, so an incorrect kernel never reaches the board. A correct
kernel then runs on your board with MBP enabled and disabled. Each attempt takes
about two minutes.""")
code('''mine = lab.mb_try(kernel)
lab.show_board_verdict(mine)''')
md("""Aim for `MBP.MAX8` in your kernel and fewer than 10 cycles per output.

<details>
<summary>See a solution</summary>

Uncomment the next line to print a kernel that reaches about 15× on the board.

</details>""")
code('''# lab.show_source(lab.MB_REPO / "fpga/pynq-z2/modelblaster/mb_ops/exercises/maxpool2d_s8_solution.c", "for (", lines=40)''')


md("""---

## Unit 5 · Schedule two models with XPU-RT

XPU-RT chooses where and when each operator runs. You will first solve a small
schedule on your instance, then compare saved schedules for two models sharing the
board's cores and memory. The instructors will demonstrate the robot, RiskyBird,
during the session.""")

md("""### 5.1 Solve a schedule for eight operators

Run the CP-SAT solver on a workload with eight dispatches. Each dispatch is one
operator invocation. The solver chooses a device and start time for each one while
respecting dependencies and device constraints.""")
code('''lab.sh("""source /etc/profile.d/xpurt.sh && cd $XPURT_ROOT && \\
XPURT_CPSAT_WORKERS=1 $XPURT_PYTHON scripts/run_xpurt_schedule.py \\
  --networks-json data/toplevel/networks_b154_gate.json \\
  --solver cpsat --profiled --cpsat-time-limit 60""", timeout=300)''')
md("Find the summary near the end of the output. The recorded run printed:\n\n" + fence(
    "makespan_us=237.87  op_deadline_miss=0 (dispatches, NOT instances)  cross_dev=0  solver_s=0.377")
   + """

The recorded solve reached an optimal schedule in 0.377 seconds. `makespan_us`
describes the schedule's duration using operator timings measured on the board.
`solver_s` measures the time your instance spent solving it.

For the same profiles and optimal solution, a faster host changes the solve time
while the schedule duration stays the same. Use the next cell to check the saved
`makespan_us` value against 237.87.""")
code("lab.check_solved_makespan(237.87)")
md("""Open the schedule plot and follow the operators across the device lanes. Each
operator's position shows when it runs and which device executes it.""")
code("lab.schedule_plot()")
md(fixes_table([
    ("The log stays quiet while the cell runs", "Python may buffer its output. Allow time for startup; the full command took about three seconds in the recorded run. Ask the instructor for help if it remains quiet for minutes."),
]))

md("""### 5.2 Measure the operator costs on your own board

The eight durations 5.1 scheduled against were measured, not estimated: each is the number
of cycles one operator invocation took on a board like yours. `--profiled` is the flag that
makes the solver read those measurements instead of modelling the operators. This section
produces them again on your own card and re-solves the same schedule from your numbers.

The image below is the detector, built to time itself. It runs SignDetLite eleven times and
prints one line per dispatch giving the dispatch id, the operator name, the kernel op it
selected, the tensor shape, and the cycles that invocation took.

It ships with the notebook instead of being rebuilt here, and that is part of the method: a
per-dispatch cycle count is a measurement of one binary. The same kernels compiled with
different options, or with a different calibration frame baked in as the test input, time
differently. The memoised softmax moves by several percent on the input alone, because how
many rows it can skip depends on the values it is handed. Pushing the image the recorded
profile was measured from is what makes the comparison below one between two boards.""")
code('''lab.board_put(lab.profile_image(), "zephyr.bin")
lab.board("bitstream", "all")
ran = lab.board("run", "zephyr", timeout=300)''')
md("""The card loads the bitstream, boots the image, and reads its console for the length of
the run.

The next cell reads that console back. It prints the image's own two summary lines first,
then one row per dispatch. The dispatch id is the join key for everything that follows:
operator names repeat inside a network, and ids do not.""")
code('''console = lab.console_text(lab.board("get", "console.out", binary=True, verbose=False))
lab.show_console_lines(console, "MB_PEXT_BUILD", "MB_PEXT_RUN")
rows = lab.measured_dispatch_rows(console)
lab.show_measured_dispatches(rows)''')
md("""The build line names the model, the number of operators in it, and how many times the
image ran the frame. The run line gives the minimum, median and maximum of those frames in
cycles, and `max_abs_err=0` says every one of them produced the expected output. These are
timings of a run that was also correct.

Compare the `cycles` column against `shipped`, the cost the schedule in 5.1 used for that
same dispatch. Both are runs of the same image under the same bitstream at the same clock, on
two different cards. The five convolutions that dominate the frame, `conv1` to `conv5`, agree
to about a tenth of one percent. The cheap dispatches vary by more, because a fixed
per-dispatch overhead is a larger share of a small number. The minimum-to-maximum spread the
run line reports across its eleven frames is of the same size as these differences, so one
run on each card cannot tell how much of them belongs to the boards and how much to
run-to-run variation.

Read down the cycles column to see where the frame goes. `conv3` and `conv5` together take
more than sixty percent of it, and both are the 3x3 convolutions that keep their spatial
size instead of halving it. `permute` costs about two thousand cycles, some 1,500 times less
than `conv5`, because it moves bytes and multiplies nothing.

The next cell converts those rows into the file the scheduler reads.""")
code('''profile = lab.write_measured_profile(rows)''')
md("""XPU-RT ingests per-dispatch costs as a `results.csv` under a directory tree named by
backend, target, model and core topology, and `scripts/uartlog_to_profile.py` is the
converter that writes one. It reads a profile block: a header naming the five fields, then
one row per dispatch. Those are the same five fields the board's console lines carry, which
is why the console needs no separate ingest path -- the rows are written into the block and
the project's own converter does the rest. It divides cycles by the clock to get the times
the CSV states, and reports the total it read.

The second machine's file is carried over from the shipped workload unchanged. Every row in
it is an exclusion rather than a cost: `conv2d_s8_pc` has no engine kernel at all, and the
kernels bound for `permute4_s8` and `softmax_s8` are built from instructions the second core
does not implement -- the same instructions the negative control in Unit 4 confirmed that
core rejects.
Those are properties of the kernel library and of the two cores' instruction sets. They are
not timings, and no board run can measure them.

Everything else in the workload is reused as it is -- the dispatch graph, the period, the
detection window -- so the only difference between the next solve and 5.1's is which cycle
counts the costs came from.""")
code('''if profile:
    lab.sh(f"""source /etc/profile.d/xpurt.sh && cd $XPURT_ROOT && \\
XPURT_CPSAT_WORKERS=1 $XPURT_PYTHON scripts/run_xpurt_schedule.py \\
  --networks-json {profile} \\
  --solver cpsat --profiled --cpsat-time-limit 60""", timeout=300)''')
md("""This is 5.1's command with your workload in place of the shipped one. Find `pdb_hash`
near the end of the output: it is a digest over the profile CSVs this solve read, so it
differs from the one 5.1 printed. The schedule was solved from different files.""")
code('''lab.compare_measured_makespan()''')
md("""The recorded run printed:

""" + fence(
    "shipped profile    makespan_us  237.87     9,514,643 cycles   op_deadline_miss 0\n"
    "your board         makespan_us  237.79     9,511,373 cycles   op_deadline_miss 0\n\n"
    "Your board ran the frame in -3,270 cycles, -0.034% of the recorded frame.") + """

The two makespans track the two cycle totals because of how this workload is placed. All
eight dispatches are pinned to the P-core, they depend on each other in a chain, and one
detection has to finish inside its window. So the schedule is the eight costs end to end, and
its duration is their sum divided by the clock. The solver starts dispatches on whole
microseconds, so the makespan can land a few microseconds above the total the table printed.
Your makespan is your measurement.

That is also the limit of what one board can change here. A profile moves a schedule when it
changes which placement is cheapest, and with one feasible placement there is nothing for it
to change. The next section is the case where it does: two models, two cores, and costs that
decide where each operator runs.""")
md(fixes_table([
    ("`board offline` or `STUB`", "Nothing ran on the card and no cell after it has data. Re-run `lab.board_status()` from Unit 1 and ask the instructor if it does not come back."),
    ("`No MB_PEXT_OP lines in that console`", "The console came back without the per-dispatch rows, so the run did not reach them. Re-run the two board cells above."),
    ("`Not written: no XPU-RT checkout on this machine`", "The conversion and the solve both need the XPU-RT install, the same one 5.1 uses. 5.3 below needs none of it."),
]))

md("""### 5.3 Compare schedules for two models

Now consider SignDetLite and Moonshine sharing two harts with different instruction
sets and a common memory system. SignDetLite runs four times at **1,000 ms intervals**.
Moonshine processes one speech job alongside those detector inferences.

A passing schedule must meet all four detector windows and finish Moonshine within
the **4,000 ms** reference time. You will compare scheduling methods and examine
compaction, a pass that moves dispatches into earlier free time slots while preserving
the schedule's constraints.

The next cells read the recorded results of that sweep and draw a comparison. They run
no solver, no XPU-RT and no board. If your checkout does not ship the recorded sweep, the
cell says so, and the printed example and the discussion below still follow.

<details>
<summary>How the experiment covers 44 configurations</summary>

Each configuration selects one option from each row:

| Setting | Options |
|---|---|
| Scheduling method | Nine heuristics and two CP-SAT paths. |
| Memory contention | `none` uses uncontended timings; `dram` includes measured DRAM contention. |
| Compaction | `plain` keeps the generated schedule; `compact` applies the compaction pass. |

These choices give 11 × 2 × 2 = 44 configurations, each with 2,285 dispatches.
Section 5.4 lets you rerun one of them.

</details>""")
code('''sweep = lab.schedule_sweep()
lab.show_headline_schedules(sweep)''')
md("""Read both Moonshine's completion time and the number of detector windows met:

""" + fence(
    "best_heuristic_makespan           4,251.12 ms   windows 1 of 4 FAILS\n"
    "only_heuristic_landing_all_four   6,076.00 ms   windows 4 of 4 FAILS\n"
    "cpsat_none_plain                  3,649.06 ms   windows 4 of 4 PASSES\n"
    "cpsat_none_compact                3,272.91 ms   windows 4 of 4 PASSES\n"
    "cpsat_dram_plain                  5,412.25 ms   windows 4 of 4 FAILS\n"
    "cpsat_dram_compact                3,992.30 ms   windows 4 of 4 PASSES\n\n"
    "cells 44 | dispatches per schedule 2,285 | machine overlaps 0"))
code("lab.schedule_comparison_figure(sweep)")
md("""Compare the CP-SAT schedules in the top panel. With measured DRAM contention,
compaction moves Moonshine's completion from 5,412.25 ms to **3,992.30 ms**, saving
1,419.95 ms and bringing it within the four-second target. Both schedules have
`op_deadline_miss_count` of 0, so all detector windows remain satisfied. Without
contention, compaction saves 376.15 ms.

The bottom panel shows the heuristic schedules. The fastest policies, `heft` and
`critical_path`, finish Moonshine at 4,251.12 ms and miss three of the four detector
windows. Only `edf` meets all four windows, but Moonshine finishes at 6,076.00 ms,
which exceeds the reference by 2,076 ms. All 36 heuristic configurations fail at least
one of the two requirements.

<details>
<summary>Why compaction helps these CP-SAT schedules</summary>

The heuristic results contain 18 pairs of plain and compact schedules. In every
pair, compaction moves 0 of 2,285 dispatches and saves 0.000 ms. The list schedulers
already place each dispatch at the earliest feasible time for their chosen order.
Their schedules leave no gaps that this pass can remove. The plot therefore shows
only the 18 plain configurations.

The CP-SAT schedules contain gaps that compaction can remove by starting dispatches
earlier while respecting their dependencies and resource constraints.

</details>

<details>
<summary>Read the detector frame rates</summary>

The fastest heuristic meets one of four detector windows, equivalent to 0.25 on-time
frames per second. A passing schedule meets all four, or 1.0 fps. The experiment also
reports a capacity estimate of 2.62 fps.

</details>""")
code('''lab.show_compaction(sweep)
lab.show_refused_cells(sweep)''')
md("""The validation report rejects four configurations with forbidden device assignments,
74 exclusion violations in all. They place `linear_s8` on a core marked infeasible by the
dispatch graph and `permute4_s8` on the hart without the P-extension. Those kernels
would execute unsupported instructions on their assigned cores.

Check device validity before comparing completion times. The shortest Moonshine
completion time across all 44 configurations, 3,272.91 ms, belongs to a valid schedule.

<details>
<summary>Why the solver allowed forbidden assignments</summary>

One CP-SAT path omits `infeasible_combinations` when building its model. It therefore
treats forbidden placements as available options with ordinary durations. The
resulting completion times can look plausible even though the assignments are invalid.

The invalid `warmbest` result is faster in only one of the four paired comparisons.
Excluding those results leaves the best valid completion time unchanged.

</details>""")

md("""### 5.4 Optional: solve one configuration

Rerun the FIFO configuration with no memory contention and no compaction. Allow
about half a minute for this heuristic run. The full 44-configuration sweep takes
hours because it includes CP-SAT solves.

The solve needs three things this repository does not carry: an XPU-RT checkout, an
interpreter with `ortools`, and that checkout's git history -- the sweep checks XPU-RT
against the revision the recorded numbers came from before it solves anything, and it
cannot check a tree that was copied rather than cloned. The cell names whichever of the
three it cannot find, and 5.3 above carries the whole result without any of them.

The first cell prepares the configuration's working directory. The supplied sweep
has a path problem and can exit successfully without producing a schedule. On the
tutorial instances the cell stops before that, on the revision check, and says so: the
supplied XPU-RT tree was copied rather than cloned. Where the cell does run and prints
`the sweep produced NO schedule`, continue with the second cell, which applies the
workaround, and check the schedule output to confirm that the solve succeeded.""")
code('''farm = lab.run_sweep_cell(policy="fifo")''')
md("""Run the solver using the copy of the script inside the configuration's own working
directory, where the previous cell prepared the input data. The solve runs only if that
directory exists.

<details>
<summary>Why the script path matters</summary>

The sweep creates a working directory containing links to XPU-RT and this tutorial's
input files. `run_xpurt_schedule.py` resolves data paths relative to its own location.
The original invocation points at the XPU-RT checkout, where the tutorial's data is
missing, and fails with `dispatch_deps_path not found at ''`.

Calling the script inside the configuration's working directory lets it find the
input files prepared there.

</details>""")
code('''lab.solve_in_sweep_cell(farm, sweep, policy="fifo")''')
md("""The recorded FIFO run matched the saved completion time and late-dispatch count:

""" + fence("makespan_us=6339.28  op_deadline_miss=21 (dispatches, NOT instances)  "
            "cross_dev=1438  solver_s=0.484\n"
            "golden says moonshine_end_ms=6339.28, late_detector_dispatches=21") + """

Compare `op_deadline_miss` with `late_detector_dispatches`: both report 21. These
misses count individual operator dispatches; a single detector inference contains
several dispatches. Your `solver_s` value will vary with the machine running the solve.""")

# ======================================================================================
# The demos
# ======================================================================================
md("""---

## Watch the live demos

The instructors will demonstrate the speech and traffic-sign models from Units 2 and 5
using live microphone and camera input. Both run on the same SoC design used throughout
the tutorial. Watch the board's indicators and display as each model processes its input.""")

md("""### Transcribe speech on the board

The demo samples the room's background noise for two seconds. The instructor then
claps to start a four-second recording and speaks into the microphone. The lamp turns
green during recording and blue during transcription. The transcript appears on the
console and display.

The board takes about **4.7 seconds to transcribe the clip after recording finishes**.
It handles one clip at a time and pauses recording during transcription. The model
weights and audio stay on the SoC; the host supplies power and a console.

<details>
<summary>Compare the live and batched speech timings</summary>

Dividing the 4.7-second compute time by the four-second audio duration gives a
real-time factor of about 1.18. Transcription takes longer than the speech itself,
even before accounting for the separate recording phase.

A separate benchmark on the same model and board reported a real-time factor of 0.89
when it processed four recordings as a batch. The decoder's matrix multiplications
have four rows, one per utterance, so each weight load serves all four. The live demo
processes one recording at a time.

</details>

<details>
<summary>How audio preprocessing affects the accuracy comparison</summary>

The batched benchmark measured word error with a 1,000-tap equalizer running on the
ARM core. The live demo image omits this equalizer. Running the benchmark without it
produced a word error rate above 20%.

</details>""")

md("""### Detect traffic signs on the board

The instructor points the camera at a sign. The board runs the detector from Unit 2
and updates its display with **STOP**, **YIELD**, or **NO SIGN**.

Model inference takes **237 to 238 ms**. Capturing, processing, and displaying a whole
frame takes about **0.55 seconds**, giving roughly 1.8 frames per second.

<details>
<summary>Where the frame time goes</summary>

The inference timing was measured over 400 runs and agrees with Unit 2's prediction
and measurement on a saved frame. Inference accounts for less than half the total
frame time. The board also converts Bayer camera data into a 64x64x3 image, performs
L2 cache maintenance so the ARM core can read the frame, and updates the display.

</details>

<details>
<summary>How the demo checks its results</summary>

At startup, the board runs eight saved camera captures through the detector and
compares its answers with reference results computed on the host. It checks the
class, grid cell, confidence, and all 192 bytes of each output tensor.

The recorded run matched **all eight decisions and all eight tensors exactly**.
Both the host and the board rejected a detection in one capture because its confidence
was too low.

</details>

<details>
<summary>Why the demo uses a higher confidence threshold</summary>

The detector reported a sign on an empty bench about half the time at its default
confidence threshold. That measurement came from one test room. The demo uses a
higher threshold to reduce false detections.

</details>""")

md("""### Instructor note: speech demo readiness

The speech demo works on the bench board. Three limitations remain:

- The build for the attendee board's bitstream exists but has not been run on hardware.
- The variant that starts recording with a button press still needs to be built and run.
- The tools read the transcript from the guest console. On attendee boards, the tool
  account lacks permission to read that console device.""")

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}
NB.write_text(json.dumps(nb, indent=1) + "\n")
print(f"wrote {NB}  ({len(cells)} cells)")
